// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AgentCreate
 */
export type AgentCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * System Prompt
     */
    system_prompt?: string;
    /**
     * Llm Model
     */
    llm_model?: string;
    /**
     * Llm Settings
     */
    llm_settings?: {
        [key: string]: unknown;
    };
    /**
     * Max Iterations
     */
    max_iterations?: number;
    /**
     * Timeout Seconds
     */
    timeout_seconds?: number;
    /**
     * Is Active
     */
    is_active?: boolean;
};

/**
 * AgentPublic
 */
export type AgentPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * System Prompt
     */
    system_prompt?: string;
    /**
     * Llm Model
     */
    llm_model?: string;
    /**
     * Llm Settings
     */
    llm_settings?: {
        [key: string]: unknown;
    };
    /**
     * Max Iterations
     */
    max_iterations?: number;
    /**
     * Timeout Seconds
     */
    timeout_seconds?: number;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Updated At
     */
    updated_at?: string | null;
    /**
     * Latest Version Number
     */
    latest_version_number?: number | null;
};

/**
 * AgentUpdate
 */
export type AgentUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * System Prompt
     */
    system_prompt?: string | null;
    /**
     * Llm Model
     */
    llm_model?: string | null;
    /**
     * Llm Settings
     */
    llm_settings?: {
        [key: string]: unknown;
    } | null;
    /**
     * Max Iterations
     */
    max_iterations?: number | null;
    /**
     * Timeout Seconds
     */
    timeout_seconds?: number | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * AgentVersionCreate
 *
 * Request body for publishing an immutable agent version.
 */
export type AgentVersionCreate = {
    /**
     * Changelog
     */
    changelog?: string | null;
};

/**
 * AgentVersionPublic
 */
export type AgentVersionPublic = {
    /**
     * Changelog
     */
    changelog?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Version Number
     */
    version_number: number;
    /**
     * Snapshot
     */
    snapshot: {
        [key: string]: unknown;
    };
    /**
     * Is Draft
     */
    is_draft: boolean;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * AgentVersionsPublic
 */
export type AgentVersionsPublic = {
    /**
     * Data
     */
    data: Array<AgentVersionPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * AgentsPublic
 */
export type AgentsPublic = {
    /**
     * Data
     */
    data: Array<AgentPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Body_login-login_access_token
 */
export type Body_login_login_access_token = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ConvMessagePublic
 */
export type ConvMessagePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Conversation Id
     */
    conversation_id: string;
    /**
     * Seq
     */
    seq: number;
    role: MessageRole;
    /**
     * Content
     */
    content: string;
    /**
     * Tool Calls
     */
    tool_calls: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Tool Call Id
     */
    tool_call_id?: string | null;
    /**
     * Token Count
     */
    token_count?: number | null;
    /**
     * Run Id
     */
    run_id?: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ConvMessagesPublic
 */
export type ConvMessagesPublic = {
    /**
     * Data
     */
    data: Array<ConvMessagePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ConversationCreate
 */
export type ConversationCreate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Agent Id
     */
    agent_id: string;
};

/**
 * ConversationPublic
 */
export type ConversationPublic = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Agent Id
     */
    agent_id: string;
    /**
     * Thread Id
     */
    thread_id: string;
    /**
     * Summary
     */
    summary?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Message Count
     */
    message_count?: number | null;
};

/**
 * ConversationUpdate
 */
export type ConversationUpdate = {
    /**
     * Title
     */
    title?: string | null;
};

/**
 * ConversationsPublic
 */
export type ConversationsPublic = {
    /**
     * Data
     */
    data: Array<ConversationPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HTTPValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * MessageRole
 */
export type MessageRole = 'user' | 'assistant' | 'tool' | 'system';

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * RunCreate
 */
export type RunCreate = {
    /**
     * Agent Version Id
     */
    agent_version_id: string;
    /**
     * Input
     */
    input?: {
        [key: string]: unknown;
    };
    trigger?: RunTrigger;
    /**
     * Conversation Id
     */
    conversation_id?: string | null;
};

/**
 * RunEventPublic
 */
export type RunEventPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Run Id
     */
    run_id: string;
    /**
     * Seq
     */
    seq: number;
    event_type: RunEventType;
    /**
     * Node Name
     */
    node_name?: string | null;
    /**
     * Payload
     */
    payload: {
        [key: string]: unknown;
    };
    /**
     * Created At
     */
    created_at: string;
};

/**
 * RunEventType
 */
export type RunEventType = 'run_started' | 'node_started' | 'node_finished' | 'model_chunk' | 'tool_called' | 'tool_result' | 'context_retrieved' | 'approval_requested' | 'approval_resolved' | 'run_finished' | 'run_failed';

/**
 * RunEventsPublic
 */
export type RunEventsPublic = {
    /**
     * Data
     */
    data: Array<RunEventPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * RunPublic
 */
export type RunPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Owner Id
     */
    owner_id: string;
    /**
     * Agent Version Id
     */
    agent_version_id: string;
    /**
     * Conversation Id
     */
    conversation_id?: string | null;
    status: RunStatus;
    trigger: RunTrigger;
    /**
     * Input
     */
    input: {
        [key: string]: unknown;
    };
    /**
     * Output
     */
    output?: {
        [key: string]: unknown;
    } | null;
    /**
     * Error
     */
    error?: string | null;
    /**
     * Started At
     */
    started_at?: string | null;
    /**
     * Finished At
     */
    finished_at?: string | null;
    /**
     * Duration Ms
     */
    duration_ms?: number | null;
    /**
     * Prompt Tokens
     */
    prompt_tokens: number;
    /**
     * Completion Tokens
     */
    completion_tokens: number;
    /**
     * Cost Usd
     */
    cost_usd?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Agent Name
     */
    agent_name?: string | null;
    /**
     * Agent Version Number
     */
    agent_version_number?: number | null;
};

/**
 * RunStatus
 */
export type RunStatus = 'queued' | 'running' | 'waiting_approval' | 'succeeded' | 'failed' | 'cancelled';

/**
 * RunTrigger
 */
export type RunTrigger = 'playground' | 'api' | 'eval';

/**
 * RunsPublic
 */
export type RunsPublic = {
    /**
     * Data
     */
    data: Array<RunPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * StreamMessageRequest
 */
export type StreamMessageRequest = {
    /**
     * Message
     */
    message: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at?: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type loginLoginAccessTokenData = {
    body: Body_login_login_access_token;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type loginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginLoginAccessTokenError = loginLoginAccessTokenErrors[keyof loginLoginAccessTokenErrors];

export type loginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type loginLoginAccessTokenResponse = loginLoginAccessTokenResponses[keyof loginLoginAccessTokenResponses];

export type loginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type loginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type loginTestTokenResponse = loginTestTokenResponses[keyof loginTestTokenResponses];

export type loginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type loginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordError = loginRecoverPasswordErrors[keyof loginRecoverPasswordErrors];

export type loginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginRecoverPasswordResponse = loginRecoverPasswordResponses[keyof loginRecoverPasswordResponses];

export type loginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type loginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginResetPasswordError = loginResetPasswordErrors[keyof loginResetPasswordErrors];

export type loginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type loginResetPasswordResponse = loginResetPasswordResponses[keyof loginResetPasswordResponses];

export type loginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type loginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type loginRecoverPasswordHtmlContentError = loginRecoverPasswordHtmlContentErrors[keyof loginRecoverPasswordHtmlContentErrors];

export type loginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type loginRecoverPasswordHtmlContentResponse = loginRecoverPasswordHtmlContentResponses[keyof loginRecoverPasswordHtmlContentResponses];

export type usersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type usersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUsersError = usersReadUsersErrors[keyof usersReadUsersErrors];

export type usersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type usersReadUsersResponse = usersReadUsersResponses[keyof usersReadUsersResponses];

export type usersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type usersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersCreateUserError = usersCreateUserErrors[keyof usersCreateUserErrors];

export type usersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersCreateUserResponse = usersCreateUserResponses[keyof usersCreateUserResponses];

export type usersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserMeResponse = usersDeleteUserMeResponses[keyof usersDeleteUserMeResponses];

export type usersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserMeResponse = usersReadUserMeResponses[keyof usersReadUserMeResponses];

export type usersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type usersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserMeError = usersUpdateUserMeErrors[keyof usersUpdateUserMeErrors];

export type usersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserMeResponse = usersUpdateUserMeResponses[keyof usersUpdateUserMeResponses];

export type usersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type usersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdatePasswordMeError = usersUpdatePasswordMeErrors[keyof usersUpdatePasswordMeErrors];

export type usersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersUpdatePasswordMeResponse = usersUpdatePasswordMeResponses[keyof usersUpdatePasswordMeResponses];

export type usersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type usersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersRegisterUserError = usersRegisterUserErrors[keyof usersRegisterUserErrors];

export type usersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersRegisterUserResponse = usersRegisterUserResponses[keyof usersRegisterUserResponses];

export type usersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersDeleteUserError = usersDeleteUserErrors[keyof usersDeleteUserErrors];

export type usersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type usersDeleteUserResponse = usersDeleteUserResponses[keyof usersDeleteUserResponses];

export type usersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersReadUserByIdError = usersReadUserByIdErrors[keyof usersReadUserByIdErrors];

export type usersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersReadUserByIdResponse = usersReadUserByIdResponses[keyof usersReadUserByIdResponses];

export type usersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type usersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type usersUpdateUserError = usersUpdateUserErrors[keyof usersUpdateUserErrors];

export type usersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type usersUpdateUserResponse = usersUpdateUserResponses[keyof usersUpdateUserResponses];

export type utilsTestEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email To
         */
        email_to: string;
    };
    url: '/api/v1/utils/test-email/';
};

export type utilsTestEmailErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type utilsTestEmailError = utilsTestEmailErrors[keyof utilsTestEmailErrors];

export type utilsTestEmailResponses = {
    /**
     * Successful Response
     */
    201: Message;
};

export type utilsTestEmailResponse = utilsTestEmailResponses[keyof utilsTestEmailResponses];

export type utilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type utilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type utilsHealthCheckResponse = utilsHealthCheckResponses[keyof utilsHealthCheckResponses];

export type agentsReadAgentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/agents/';
};

export type agentsReadAgentsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentsReadAgentsError = agentsReadAgentsErrors[keyof agentsReadAgentsErrors];

export type agentsReadAgentsResponses = {
    /**
     * Successful Response
     */
    200: AgentsPublic;
};

export type agentsReadAgentsResponse = agentsReadAgentsResponses[keyof agentsReadAgentsResponses];

export type agentsCreateAgentData = {
    body: AgentCreate;
    path?: never;
    query?: never;
    url: '/api/v1/agents/';
};

export type agentsCreateAgentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentsCreateAgentError = agentsCreateAgentErrors[keyof agentsCreateAgentErrors];

export type agentsCreateAgentResponses = {
    /**
     * Successful Response
     */
    200: AgentPublic;
};

export type agentsCreateAgentResponse = agentsCreateAgentResponses[keyof agentsCreateAgentResponses];

export type agentsDeleteAgentData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/agents/{id}';
};

export type agentsDeleteAgentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentsDeleteAgentError = agentsDeleteAgentErrors[keyof agentsDeleteAgentErrors];

export type agentsDeleteAgentResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type agentsDeleteAgentResponse = agentsDeleteAgentResponses[keyof agentsDeleteAgentResponses];

export type agentsReadAgentData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/agents/{id}';
};

export type agentsReadAgentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentsReadAgentError = agentsReadAgentErrors[keyof agentsReadAgentErrors];

export type agentsReadAgentResponses = {
    /**
     * Successful Response
     */
    200: AgentPublic;
};

export type agentsReadAgentResponse = agentsReadAgentResponses[keyof agentsReadAgentResponses];

export type agentsUpdateAgentData = {
    body: AgentUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/agents/{id}';
};

export type agentsUpdateAgentErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentsUpdateAgentError = agentsUpdateAgentErrors[keyof agentsUpdateAgentErrors];

export type agentsUpdateAgentResponses = {
    /**
     * Successful Response
     */
    200: AgentPublic;
};

export type agentsUpdateAgentResponse = agentsUpdateAgentResponses[keyof agentsUpdateAgentResponses];

export type agentsReadVersionsData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/agents/{id}/versions';
};

export type agentsReadVersionsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentsReadVersionsError = agentsReadVersionsErrors[keyof agentsReadVersionsErrors];

export type agentsReadVersionsResponses = {
    /**
     * Successful Response
     */
    200: AgentVersionsPublic;
};

export type agentsReadVersionsResponse = agentsReadVersionsResponses[keyof agentsReadVersionsResponses];

export type agentsPublishVersionData = {
    body: AgentVersionCreate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/agents/{id}/versions';
};

export type agentsPublishVersionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentsPublishVersionError = agentsPublishVersionErrors[keyof agentsPublishVersionErrors];

export type agentsPublishVersionResponses = {
    /**
     * Successful Response
     */
    200: AgentVersionPublic;
};

export type agentsPublishVersionResponse = agentsPublishVersionResponses[keyof agentsPublishVersionResponses];

export type agentsReadVersionData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
        /**
         * Version Id
         */
        version_id: string;
    };
    query?: never;
    url: '/api/v1/agents/{id}/versions/{version_id}';
};

export type agentsReadVersionErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type agentsReadVersionError = agentsReadVersionErrors[keyof agentsReadVersionErrors];

export type agentsReadVersionResponses = {
    /**
     * Successful Response
     */
    200: AgentVersionPublic;
};

export type agentsReadVersionResponse = agentsReadVersionResponses[keyof agentsReadVersionResponses];

export type runsReadRunsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Agent Version Id
         */
        agent_version_id?: string | null;
        /**
         * Status
         */
        status?: RunStatus | null;
    };
    url: '/api/v1/runs/';
};

export type runsReadRunsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type runsReadRunsError = runsReadRunsErrors[keyof runsReadRunsErrors];

export type runsReadRunsResponses = {
    /**
     * Successful Response
     */
    200: RunsPublic;
};

export type runsReadRunsResponse = runsReadRunsResponses[keyof runsReadRunsResponses];

export type runsCreateRunData = {
    body: RunCreate;
    path?: never;
    query?: never;
    url: '/api/v1/runs/';
};

export type runsCreateRunErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type runsCreateRunError = runsCreateRunErrors[keyof runsCreateRunErrors];

export type runsCreateRunResponses = {
    /**
     * Successful Response
     */
    200: RunPublic;
};

export type runsCreateRunResponse = runsCreateRunResponses[keyof runsCreateRunResponses];

export type runsReadRunData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/runs/{id}';
};

export type runsReadRunErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type runsReadRunError = runsReadRunErrors[keyof runsReadRunErrors];

export type runsReadRunResponses = {
    /**
     * Successful Response
     */
    200: RunPublic;
};

export type runsReadRunResponse = runsReadRunResponses[keyof runsReadRunResponses];

export type runsReadEventsData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/runs/{id}/events';
};

export type runsReadEventsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type runsReadEventsError = runsReadEventsErrors[keyof runsReadEventsErrors];

export type runsReadEventsResponses = {
    /**
     * Successful Response
     */
    200: RunEventsPublic;
};

export type runsReadEventsResponse = runsReadEventsResponses[keyof runsReadEventsResponses];

export type conversationsReadConversationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Agent Id
         */
        agent_id?: string | null;
    };
    url: '/api/v1/conversations/';
};

export type conversationsReadConversationsErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conversationsReadConversationsError = conversationsReadConversationsErrors[keyof conversationsReadConversationsErrors];

export type conversationsReadConversationsResponses = {
    /**
     * Successful Response
     */
    200: ConversationsPublic;
};

export type conversationsReadConversationsResponse = conversationsReadConversationsResponses[keyof conversationsReadConversationsResponses];

export type conversationsCreateConversationData = {
    body: ConversationCreate;
    path?: never;
    query?: never;
    url: '/api/v1/conversations/';
};

export type conversationsCreateConversationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conversationsCreateConversationError = conversationsCreateConversationErrors[keyof conversationsCreateConversationErrors];

export type conversationsCreateConversationResponses = {
    /**
     * Successful Response
     */
    200: ConversationPublic;
};

export type conversationsCreateConversationResponse = conversationsCreateConversationResponses[keyof conversationsCreateConversationResponses];

export type conversationsDeleteConversationData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/conversations/{id}';
};

export type conversationsDeleteConversationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conversationsDeleteConversationError = conversationsDeleteConversationErrors[keyof conversationsDeleteConversationErrors];

export type conversationsDeleteConversationResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type conversationsDeleteConversationResponse = conversationsDeleteConversationResponses[keyof conversationsDeleteConversationResponses];

export type conversationsReadConversationData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/conversations/{id}';
};

export type conversationsReadConversationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conversationsReadConversationError = conversationsReadConversationErrors[keyof conversationsReadConversationErrors];

export type conversationsReadConversationResponses = {
    /**
     * Successful Response
     */
    200: ConversationPublic;
};

export type conversationsReadConversationResponse = conversationsReadConversationResponses[keyof conversationsReadConversationResponses];

export type conversationsUpdateConversationData = {
    body: ConversationUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/api/v1/conversations/{id}';
};

export type conversationsUpdateConversationErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conversationsUpdateConversationError = conversationsUpdateConversationErrors[keyof conversationsUpdateConversationErrors];

export type conversationsUpdateConversationResponses = {
    /**
     * Successful Response
     */
    200: ConversationPublic;
};

export type conversationsUpdateConversationResponse = conversationsUpdateConversationResponses[keyof conversationsUpdateConversationResponses];

export type conversationsReadMessagesData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/conversations/{id}/messages';
};

export type conversationsReadMessagesErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conversationsReadMessagesError = conversationsReadMessagesErrors[keyof conversationsReadMessagesErrors];

export type conversationsReadMessagesResponses = {
    /**
     * Successful Response
     */
    200: ConvMessagesPublic;
};

export type conversationsReadMessagesResponse = conversationsReadMessagesResponses[keyof conversationsReadMessagesResponses];

export type conversationsStreamMessageData = {
    body: StreamMessageRequest;
    path: {
        /**
         * Conversation Id
         */
        conversation_id: string;
    };
    query?: never;
    url: '/api/v1/conversations/{conversation_id}/stream';
};

export type conversationsStreamMessageErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type conversationsStreamMessageError = conversationsStreamMessageErrors[keyof conversationsStreamMessageErrors];

export type conversationsStreamMessageResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type privateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type privateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HTTPValidationError;
};

export type privateCreateUserError = privateCreateUserErrors[keyof privateCreateUserErrors];

export type privateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type privateCreateUserResponse = privateCreateUserResponses[keyof privateCreateUserResponses];
