"""Add approval request model

Revision ID: 1b01bc705599
Revises: dcfa86559b4f
Create Date: 2026-09-18 14:55:07.988275

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b01bc705599'
down_revision = 'dcfa86559b4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_request',
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('tool_call_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('tool_args', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('checkpoint_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'checkpoint_id', 'tool_call_id')
    )
    op.create_index(op.f('ix_approval_request_owner_id'), 'approval_request', ['owner_id'], unique=False)
    op.create_index(op.f('ix_approval_request_run_id'), 'approval_request', ['run_id'], unique=False)
    op.create_index(op.f('ix_approval_request_status'), 'approval_request', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_request_status'), table_name='approval_request')
    op.drop_index(op.f('ix_approval_request_run_id'), table_name='approval_request')
    op.drop_index(op.f('ix_approval_request_owner_id'), table_name='approval_request')
    op.drop_table('approval_request')
    # ### end Alembic commands ###
