"""Add tool and agent tool binding models

Revision ID: 6b47e6b4b2fe
Revises: ef6ffc70036a
Create Date: 2026-09-17 16:04:56.187987

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6b47e6b4b2fe'
down_revision = 'ef6ffc70036a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('tool_type', sa.String(length=32), nullable=False),
    sa.Column('parameters_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'name')
    )
    op.create_index(op.f('ix_tool_owner_id'), 'tool', ['owner_id'], unique=False)
    op.create_table('agent_tool_binding',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_version_id', sa.Uuid(), nullable=False),
    sa.Column('tool_id', sa.Uuid(), nullable=False),
    sa.Column('config_override', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_version_id', 'tool_id')
    )
    op.create_index(op.f('ix_agent_tool_binding_agent_version_id'), 'agent_tool_binding', ['agent_version_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_binding_tool_id'), 'agent_tool_binding', ['tool_id'], unique=False)
    op.add_column('agent', sa.Column('tool_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'tool_ids')
    op.drop_index(op.f('ix_agent_tool_binding_tool_id'), table_name='agent_tool_binding')
    op.drop_index(op.f('ix_agent_tool_binding_agent_version_id'), table_name='agent_tool_binding')
    op.drop_table('agent_tool_binding')
    op.drop_index(op.f('ix_tool_owner_id'), table_name='tool')
    op.drop_table('tool')
    # ### end Alembic commands ###
