"""Add agent and agent version models

Revision ID: b71a4cc35e71
Revises: 88cdef47b355
Create Date: 2026-09-12 01:37:14.740906

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b71a4cc35e71'
down_revision = '88cdef47b355'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('system_prompt', sqlmodel.sql.sqltypes.AutoString(length=20000), nullable=False),
    sa.Column('llm_model', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('llm_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_owner_id'), 'agent', ['owner_id'], unique=False)
    op.create_table('agent_version',
    sa.Column('changelog', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_draft', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'version_number')
    )
    op.create_index(op.f('ix_agent_version_agent_id'), 'agent_version', ['agent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_version_agent_id'), table_name='agent_version')
    op.drop_table('agent_version')
    op.drop_index(op.f('ix_agent_owner_id'), table_name='agent')
    op.drop_table('agent')
    # ### end Alembic commands ###
