"""Add run retry count

Revision ID: dcfa86559b4f
Revises: 6b47e6b4b2fe
Create Date: 2026-09-17 18:59:33.370438

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'dcfa86559b4f'
down_revision = '6b47e6b4b2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('run', 'retry_count')
    # ### end Alembic commands ###
