"""Add agent knowledge base bindings

Revision ID: e2e7bfca120f
Revises: 17077dabb662
Create Date: 2026-09-18 16:04:04.929369

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2e7bfca120f'
down_revision = '17077dabb662'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent', sa.Column('knowledge_base_ids', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent', 'knowledge_base_ids')
    # ### end Alembic commands ###
