"""Add conversation and message models

Revision ID: ef6ffc70036a
Revises: fc80b27cb09a
Create Date: 2026-09-16 22:10:59.319916

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef6ffc70036a'
down_revision = 'fc80b27cb09a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(length=8000), nullable=True),
    sa.Column('summarized_up_to_seq', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_agent_id'), 'conversation', ['agent_id'], unique=False)
    op.create_index(op.f('ix_conversation_owner_id'), 'conversation', ['owner_id'], unique=False)
    op.create_index(op.f('ix_conversation_thread_id'), 'conversation', ['thread_id'], unique=True)
    op.create_table('message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_call_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'seq')
    )
    op.create_index(op.f('ix_message_conversation_id'), 'message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_message_run_id'), 'message', ['run_id'], unique=False)
    op.create_foreign_key('run_conversation_id_fkey', 'run', 'conversation', ['conversation_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('run_conversation_id_fkey', 'run', type_='foreignkey')
    op.drop_index(op.f('ix_message_run_id'), table_name='message')
    op.drop_index(op.f('ix_message_conversation_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_conversation_thread_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_owner_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_agent_id'), table_name='conversation')
    op.drop_table('conversation')
    # ### end Alembic commands ###
