"""Add run and run event models

Revision ID: fc80b27cb09a
Revises: 93c88b62686b
Create Date: 2026-09-12 18:01:12.833379

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc80b27cb09a'
down_revision = '93c88b62686b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('run',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('agent_version_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=4000), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('checkpoint_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_version.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_run_agent_version_id'), 'run', ['agent_version_id'], unique=False)
    op.create_index(op.f('ix_run_conversation_id'), 'run', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_run_owner_id'), 'run', ['owner_id'], unique=False)
    op.create_index(op.f('ix_run_status'), 'run', ['status'], unique=False)
    op.create_index(op.f('ix_run_thread_id'), 'run', ['thread_id'], unique=False)
    op.create_table('run_event',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('node_name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'seq')
    )
    op.create_index(op.f('ix_run_event_run_id'), 'run_event', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_run_event_run_id'), table_name='run_event')
    op.drop_table('run_event')
    op.drop_index(op.f('ix_run_thread_id'), table_name='run')
    op.drop_index(op.f('ix_run_status'), table_name='run')
    op.drop_index(op.f('ix_run_owner_id'), table_name='run')
    op.drop_index(op.f('ix_run_conversation_id'), table_name='run')
    op.drop_index(op.f('ix_run_agent_version_id'), table_name='run')
    op.drop_table('run')
    # ### end Alembic commands ###
