/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutAgentsRouteImport } from './routes/_layout/agents'
import { Route as LayoutPlaygroundRouteImport } from './routes/_layout/playground'
import { Route as LayoutRunsRouteImport } from './routes/_layout/runs'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutAgentsAgentIdRouteImport } from './routes/_layout/agents.$agentId'
import { Route as LayoutRunsRunIdRouteImport } from './routes/_layout/runs.$runId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsRoute = LayoutAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlaygroundRoute = LayoutPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRunsRoute = LayoutRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAgentsAgentIdRoute = LayoutAgentsAgentIdRouteImport.update({
  id: '/$agentId',
  path: '/$agentId',
  getParentRoute: () => LayoutAgentsRoute,
} as any)
const LayoutRunsRunIdRoute = LayoutRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => LayoutRunsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/agents': typeof LayoutAgentsRouteWithChildren
  '/playground': typeof LayoutPlaygroundRoute
  '/runs': typeof LayoutRunsRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/agents/$agentId': typeof LayoutAgentsAgentIdRoute
  '/runs/$runId': typeof LayoutRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/agents': typeof LayoutAgentsRouteWithChildren
  '/playground': typeof LayoutPlaygroundRoute
  '/runs': typeof LayoutRunsRouteWithChildren
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/agents/$agentId': typeof LayoutAgentsAgentIdRoute
  '/runs/$runId': typeof LayoutRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/agents': typeof LayoutAgentsRouteWithChildren
  '/_layout/playground': typeof LayoutPlaygroundRoute
  '/_layout/runs': typeof LayoutRunsRouteWithChildren
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/agents/$agentId': typeof LayoutAgentsAgentIdRoute
  '/_layout/runs/$runId': typeof LayoutRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/agents'
    | '/playground'
    | '/runs'
    | '/settings'
    | '/agents/$agentId'
    | '/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/agents'
    | '/playground'
    | '/runs'
    | '/settings'
    | '/'
    | '/agents/$agentId'
    | '/runs/$runId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/agents'
    | '/_layout/playground'
    | '/_layout/runs'
    | '/_layout/settings'
    | '/_layout/'
    | '/_layout/agents/$agentId'
    | '/_layout/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents': {
      id: '/_layout/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof LayoutAgentsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/playground': {
      id: '/_layout/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof LayoutPlaygroundRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/runs': {
      id: '/_layout/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof LayoutRunsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/agents/$agentId': {
      id: '/_layout/agents/$agentId'
      path: '/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof LayoutAgentsAgentIdRouteImport
      parentRoute: typeof LayoutAgentsRoute
    }
    '/_layout/runs/$runId': {
      id: '/_layout/runs/$runId'
      path: '/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof LayoutRunsRunIdRouteImport
      parentRoute: typeof LayoutRunsRoute
    }
  }
}

interface LayoutAgentsRouteChildren {
  LayoutAgentsAgentIdRoute: typeof LayoutAgentsAgentIdRoute
}

const LayoutAgentsRouteChildren: LayoutAgentsRouteChildren = {
  LayoutAgentsAgentIdRoute: LayoutAgentsAgentIdRoute,
}

const LayoutAgentsRouteWithChildren = LayoutAgentsRoute._addFileChildren(
  LayoutAgentsRouteChildren,
)

interface LayoutRunsRouteChildren {
  LayoutRunsRunIdRoute: typeof LayoutRunsRunIdRoute
}

const LayoutRunsRouteChildren: LayoutRunsRouteChildren = {
  LayoutRunsRunIdRoute: LayoutRunsRunIdRoute,
}

const LayoutRunsRouteWithChildren = LayoutRunsRoute._addFileChildren(
  LayoutRunsRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAgentsRoute: typeof LayoutAgentsRouteWithChildren
  LayoutPlaygroundRoute: typeof LayoutPlaygroundRoute
  LayoutRunsRoute: typeof LayoutRunsRouteWithChildren
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAgentsRoute: LayoutAgentsRouteWithChildren,
  LayoutPlaygroundRoute: LayoutPlaygroundRoute,
  LayoutRunsRoute: LayoutRunsRouteWithChildren,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
